// templates/react/src/pages/User/Register/index.js
import './index.less';

import { connect } from '~/plugins';
import { Toast } from '~/components';
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import PropTypes from 'prop-types';
import { Button, Form, Icon, Input, Popover, Progress, Select, Row, Col } from 'antd';

import reducer, * as actions from './state';

const passwordProgressMap = {
  ok: 'success',
  pass: 'normal',
  poor: 'exception',
};

@Form.create()
@connect(
  (state) => {
    return state.userRegister;
  },
  actions
)
class UserRegister extends Component {
  static propTypes = {
    form: PropTypes.object,
    setState: PropTypes.func.isRequired,
  }

  state = {
    visiblePasswordPopover: false,
    mobilePrefix: '+86',
    countdown: 0,
  }

  componentDidMount = () => {
    this.emailInput.focus();
  }

  $i18nPath = 'userRegister'

  register = () => {
    this.props.form.validateFields(async (err, values) => {
      if (!err) {
        await this.props.register(values);
      }
    });
  }

  getPasswordStatus = () => {
    const { form } = this.props;
    const value = form.getFieldValue('password');
    if (value && value.length > 9) {
      return 'ok';
    }
    if (value && value.length > 5) {
      return 'pass';
    }
    return 'poor';
  };

  validPassword = (rule, value, callback) => {
    const { visible } = this.state;
    if (!visible) {
      this.setState({
        visible: !!value,
      });
    }
    if (value.length < 6) {
      callback('error');
    } else {
      callback();
    }
  };

  validConfirmPassword = (rule, value, callback) => {
    const { form } = this.props;
    if (value && value !== form.getFieldValue('password')) {
      callback(this.$i18n('inequalityTwicePassword'));
    } else {
      callback();
    }
  };

  onChangeText = (e) => {
    this.props.setState({ [e.target.name]: e.target.value });
  }

  onPressEnterUsername = () => {
    this.passwordInput.focus();
  }

  onPressEnterPassword = () => {
    this.confirmPasswordInput.focus();
  }

  onPressEnterConfirmPassword = () => {
    this.mobileInput.focus();
  }

  onPressEnterMobile = () => {
    this.captchaInput.focus();
  }

  onPressEnterCaptcha = () => {
    this.register();
  }

  onChangeMobilePrefix = (value) => {
    this.setState({ mobilePrefix: value });
  };

  onFetchCaptcha = () => {

  }

  renderPasswordStatus = () => {
    const status = this.getPasswordStatus();
    const passwordStatusMap = {
      ok: (
        <div className="user-register-success">
          {this.$i18n('passwordStrengthStrong')}
        </div>
      ),
      pass: (
        <div className="user-register-warning">
          {this.$i18n('passwordStrengthMedium')}
        </div>
      ),
      poor: (
        <div className="user-register-error">
          {this.$i18n('passwordStrengthPoor')}
        </div>
      ),
    };

    return passwordStatusMap[status];
  }

  renderPasswordProgress = () => {
    const { form } = this.props;
    const value = form.getFieldValue('password');
    const passwordStatus = this.getPasswordStatus();
    return value && value.length ? (
      <div className={`progress-${passwordStatus}`}>
        <Progress
          status={passwordProgressMap[passwordStatus]}
          className="user-register-progress"
          strokeWidth={6}
          percent={value.length * 10 > 100 ? 100 : value.length * 10}
          showInfo={false}
        />
      </div>
    ) : null;
  };

  render = () => {
    const { getFieldDecorator } = this.props.form;
    const { visiblePasswordPopover, mobilePrefix, countdown, password, confirmPassword } = this.state;

    const emailDecorator = getFieldDecorator('email', { rules: [
      {
        required: true,
        message: this.$i18n('requiredEmail'),
      },
      {
        type: 'email',
        message: this.$i18n('invalidEmail'),
      },
    ] });
    const passwordDecorator = getFieldDecorator('password', { rules: [
      {
        required: true,
        message: this.$i18n('requiredPassword'),
      },
      {
        validator: this.validPassword,
      },
    ] });
    const confirmPasswordDecorator = getFieldDecorator('confirmPassword', { rules: [
      {
        required: true,
        message: this.$i18n('requiredConfirmPassword'),
      },
      {
        validator: this.validConfirmPassword,
      },
    ] });
    const mobileDecorator = getFieldDecorator('mobile', {
      rules: [
        {
          required: true,
          message: this.$i18n('requiredMobile'),
        },
        {
          pattern: /^\d{11}$/,
          message: this.$i18n('invalidMobile'),
        },
      ],
    });
    const captchaDecorator = getFieldDecorator('captcha', {
      rules: [
        {
          required: true,
          message: this.$i18n('requiredCaptcha'),
        },
      ],
    });

    return (
      <div className="account-register-container">
        <div className="form register-form">
          <Form.Item>
            {
              emailDecorator(<Input
                ref={(input) => { this.emailInput = input; }}
                prefix={<Icon type="mail" className="input-prefix-icon" />}
                size="large"
                name="email"
                placeholder={this.$i18n('placeholderEmail')}
                onChange={this.onChangeText}
                onPressEnter={this.onPressEnterEmail}
              />)
            }
          </Form.Item>
          <Form.Item>
            <Popover
              getPopupContainer={node => node.parentNode}
              content={
                (
                  <div className="user-register-password-popover">
                    {this.renderPasswordStatus()}
                    {this.renderPasswordProgress()}
                    <div className="user-register-password-popover-desc">
                      {this.$i18n('passwordStrengthDesc', 6)}
                    </div>
                  </div>
                )
              }
              overlayStyle={{ width: 240 }}
              placement="right"
              visible={visiblePasswordPopover}
            >
              {
                passwordDecorator(<Input
                  ref={(input) => { this.passwordInput = input; }}
                  prefix={<Icon type="lock" className="input-prefix-icon" />}
                  size="large"
                  type="password"
                  name="password"
                  placeholder={this.$i18n('placeholderPassword', 6)}
                  onChange={this.onChangeText}
                  onPressEnter={this.onPressEnterPassword}
                  suffix={password ? <Icon type="eye" className="input-suffix-icon" /> : null}
                />)
              }
            </Popover>
          </Form.Item>
          <Form.Item>
            {
              confirmPasswordDecorator(<Input
                ref={(input) => { this.confirmPasswordInput = input; }}
                prefix={<Icon type="lock" className="input-prefix-icon" />}
                size="large"
                type="password"
                name="confirmPassword"
                placeholder={this.$i18n('placeholderConfirmPassword')}
                onChange={this.onChangeText}
                onPressEnter={this.onPressEnterConfirmPassword}
                suffix={confirmPassword ? <Icon type="eye" className="input-suffix-icon" /> : null}
              />)
            }
          </Form.Item>
          <Form.Item>
            <Input.Group compact>
              <Select
                size="large"
                value={mobilePrefix}
                onChange={this.onChangeMobilePrefix}
                style={{ width: '20%' }}
              >
                <Select.Option value="86">+86</Select.Option>
                <Select.Option value="87">+87</Select.Option>
              </Select>
              {
                mobileDecorator(
                  <Input
                    ref={(input) => { this.mobileInput = input; }}
                    size="large"
                    name="mobile"
                    placeholder={this.$i18n('placeholderMobile')}
                    onChange={this.onChangeText}
                    onPressEnter={this.onPressEnterMobile}
                    style={{ width: '80%' }}
                  />
                )
              }
            </Input.Group>
          </Form.Item>
          <Form.Item>
            <Row gutter={8}>
              <Col span={16}>
                {
                  captchaDecorator(
                    <Input
                      ref={(input) => { this.captchaInput = input; }}
                      prefix={<Icon type="key" className="input-prefix-icon" />}
                      size="large"
                      name="captcha"
                      placeholder={this.$i18n('placeholderCaptcha')}
                      onChange={this.onChangeText}
                      onPressEnter={this.onPressEnterCaptcha}
                    />
                  )
                }
              </Col>
              <Col span={8}>
                <Button
                  size="large"
                  disabled={countdown}
                  className="btn-captcha"
                  onClick={this.onFetchCaptcha}
                >
                  {countdown ? `${countdown} s` : this.$i18n('btnCaptcha') }
                </Button>
              </Col>
            </Row>
          </Form.Item>
          <Form.Item>
            <Row gutter={8}>
              <Col span={16}>
                <Button size="large" type="primary" onClick={this.register}>
                  {this.$i18n('register')}
                </Button>
              </Col>
              <Col span={8}>
                <Link to="/user/login">
                  {this.$i18n('signin')}
                </Link>
              </Col>
            </Row>
          </Form.Item>
        </div>
      </div>
    );
  }
}

export {
  reducer,
};

export default UserRegister;

// templates/vue/src/pages/User/Register/index.vue
<template>
  <div class="user-register-container">
    <a-form class="form register-form" :form="registerForm" @submit="onRegister">
      <a-form-item>
        <a-input
          v-decorator="[
            'email',
            {
              rules: [
                { required: true, message: $_i18n('requiredEmail') },
                { type: 'email', message: $_i18n('invalidEmail') }
              ]
            }
          ]"
          size="large"
          name="email"
          :placeholder="$_i18n('placeholderEmail')"
        >
          <a-icon slot="prefix" type="mail" class="input-prefix-icon" />
        </a-input>
      </a-form-item>

      <a-form-item>
        <a-popover
          :get-popup-container="node => node.parentNode"
          placement="right"
          :overlay-style="{ width: '240px' }"
          :visible="visiblePasswordPopover"
        >
          <template slot="content">
            <div class="user-register-password-popover">
              <div
                v-if="passwordStatus === 'ok'"
                class="user-register-success"
                v-text="$_i18n('passwordStrengthStrong')"
              />
              <div
                v-if="passwordStatus === 'pass'"
                class="user-register-warning"
                v-text="$_i18n('passwordStrengthMedium')"
              />
              <div
                v-if="passwordStatus === 'poor'"
                class="user-register-error"
                v-text="$_i18n('passwordStrengthPoor')"
              />
              <div v-if="password && password.length" :class="`progress-${passwordStatus}`">
                <a-progress
                  :status="passwordProgressMap[passwordStatus]"
                  class="user-register-progress"
                  :stroke-width="6"
                  :percent="password.length * 10 > 100 ? 100 : password.length * 10"
                  :show-info="false"
                />
              </div>
              <div class="user-register-password-popover-desc" v-text="$_i18n('passwordStrengthDesc', 6)" />
            </div>
          </template>
          <a-input
            v-decorator="[
              'password',
              {
                rules: [
                  { required: true, message: $_i18n('requiredPassword') },
                  { validator: validPassword }
                ]
              }
            ]"
            size="large"
            name="password"
            type="password"
            :placeholder="$_i18n('placeholderPassword', 6)"
            @change="onChangeText"
          >
            <a-icon slot="prefix" type="lock" class="input-prefix-icon" />
            <a-icon v-if="password" slot="suffix" type="eye" class="input-suffix-icon" />
          </a-input>
        </a-popover>
      </a-form-item>

      <a-form-item>
        <a-input
          v-decorator="[
            'confirmPassword',
            {
              rules: [
                { required: true, message: $_i18n('requiredConfirmPassword') },
                { validator: validConfirmPassword }
              ]
            }
          ]"
          size="large"
          name="confirmPassword"
          type="password"
          :placeholder="$_i18n('placeholderConfirmPassword')"
          @change="onChangeText"
        >
          <a-icon slot="prefix" type="lock" class="input-prefix-icon" />
          <a-icon v-if="confirmPassword" slot="suffix" type="eye" class="input-suffix-icon" />
        </a-input>
      </a-form-item>
      <a-form-item>
        <a-input-group :compact="true">
          <a-select
            size="large"
            :value="mobilePrefix"
            :style="{width: '20%'}"
            @change="onChangeMobilePrefix"
          >
            <a-select-option value="86">+86</a-select-option>
            <a-select-option value="87">+87</a-select-option>
          </a-select>
          <a-input
            v-decorator="[
              'mobile',
              {
                rules: [
                  { required: true, message: $_i18n('requiredMobile') },
                  { pattern: /^\d{11}$/, message: $_i18n('invalidMobile') }
                ]
              }
            ]"
            size="large"
            name="mobile"
            :placeholder="$_i18n('placeholderMobile')"
            :style="{ width: '80%' }"
          />
        </a-input-group>
      </a-form-item>

      <a-form-item>
        <a-row :gutter="8">
          <a-col :span="16">
            <a-input
              v-decorator="[
                'captcha',
                { rules: [{ required: true, message: $_i18n('requiredCaptcha') }]}
              ]"
              size="large"
              name="captcha"
              :placeholder="$_i18n('placeholderCaptcha')"
            />
          </a-col>
          <a-col :span="8">
            <a-button
              size="large"
              :disabled="!!countdown"
              class="btn-captcha"
              @click="onFetchCaptcha"
              v-text="countdown ? `${countdown} s` : $_i18n('btnCaptcha') "
            />
          </a-col>
        </a-row>
      </a-form-item>

      <a-form-item>
        <a-row :gutter="8">
          <a-col :span="16">
            <a-button size="large" type="primary" @click="onRegister" v-text="$_i18n('register')" />
          </a-col>
          <a-col :span="8">
            <router-link :to="{ name: 'Login' }" v-text="$_i18n('signin')" />
          </a-col>
        </a-row>
      </a-form-item>
    </a-form>
  </div>
</template>

<script>
export default {
  name: 'RegisterContainer',
  components: {
  },
  data() {
    return {
      $i18nPath: 'userRegister',
      visiblePasswordPopover: false,
      mobilePrefix: '+86',
      countdown: 0,
      registerForm: this.$form.createForm(this),
      passwordProgressMap: {
        ok: 'success',
        pass: 'normal',
        poor: 'exception',
      },
      password: '',
      confirmPassword: '',
    };
  },
  computed: {
    passwordStatus() {
      const { password } = this;
      if (password && password.length > 9) {
        return 'ok';
      }
      if (password && password.length > 5) {
        return 'pass';
      }
      return 'poor';
    }
  },
  created() {
  },
  methods: {
    validPassword(rule, value, callback) {
      const { visiblePasswordPopover } = this;

      if (!visiblePasswordPopover) {
        this.visiblePasswordPopover = !!value;
      }

      if (value.length < 6) {
        callback(this.$_i18n('placeholderPassword', 6));
        return;
      }

      callback();
    },
    validConfirmPassword(rule, value, callback) {
      const { registerForm } = this;
      if (value && value !== registerForm.getFieldValue('confirmPassword')) {
        callback(this.$_i18n('inequalityTwicePassword'));
        return;
      }

      callback();
    },
    onRegister() {

    },
    onChangeText(e) {
      this[e.target.name] = e.target.value;
    },
    onChangeMobilePrefix(value) {
      this.mobilePrefix = value;
    },
    onFetchCaptcha() {

    }
  }
};
</script>

<style rel="stylesheet/less" lang="less" scoped>
@import 'styles/variables.less';

.user-register-container {
  width: 100%;
  height: 100%;

  .form {
    width: 30vw;
    min-width: 250px;
    margin: 0 auto;
    margin-top: 50px;

    .ant-form-item {
      margin-bottom: 25px;

      &.slimming-form-item {
        .ant-form-item-control {
          line-height: 1.2;
        }
      }
    }

    a {
      float: right;
      font-size: 14px;
    }

    button {
      width: 100%;
    }

    .alert {
      margin-bottom: 20px;
    }

    .input-suffix-icon,
    .input-prefix-icon {
      color: @black-25;
    }
  }
}
</style>
